site_name: Сайт Валерии Борисовой
site_description: Персональный сайт-портфолио
site_author: Валерия Борисова

theme:
  name: material
  language: ru

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

  palette:
    - scheme: default
      primary: indigo
      accent: pink

    - scheme: slate
      primary: grey
      accent: blue-grey

  logo: images/logo.png
  favicon: images/logo.png

nav:
  - Главная: index.md
  - О себе: about/index.md
  - Проекты: projects/index.md
  - Контакты: contacts/index.md
  - Достижения: achievements/index.md

extra:
  social:
    - icon: simple/github
      link: https://github.com/vsnikitina2001-ops
      name: GitHub

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

copyright: © 2026 Валерия Борисова
